color_scheme: dark
mermaid:
  version: "10.1.0"
# Opciones de navegación
just_the_docs:
  aux_nav:
    "Inicio":
      url: /

footer_content: "Diego J. Gonzalez"
remote_theme: just-the-docs/just-the-docs
title: "Diego J. González"


