heat_template_version: newton

description: 1 equipo

parameters:
  flavor:
    type: string
    default: "m1.mini"
  image:
    type: string
    default: "51b38ecf-99e1-46a3-a497-9e1cc9c3c2d4"
  red_externa:
    type: string
    description: red para conectarse a internet
    constraints:
      - custom_constraint: neutron.network

  key_name:
    type: string
    description: SSH key pair
    constraints:
      - custom_constraint: nova.keypair
  
resources:
 
  

  r1_network_ext:
    type: OS::Neutron::Port
    properties:
      network: {get_param: red_externa}
      device_owner: "compute:nova"
      port_security_enabled: False
      security_groups: []
  
  r1:
    type: OS::Nova::Server
    properties:
      name: "maquina"
      flavor: { get_param: flavor }
      image: { get_param: image }
      key_name: { get_param: key_name }
      networks:
        - { port: { get_resource: r1_network_ext } }
      user_data: |
          #!/bin/bash -v
          apt update
          apt install -y apache2 curl dnsutils

  r1_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: ext-net
      port_id: { get_resource: r1_network_ext  }

outputs:
  
